{% set version = "3.6" %}

package:
    name: ckanapi
    version: {{ version }}

source:
    fn: ckanapi-{{ version }}.tar.gz
    url: https://github.com/ckan/ckanapi/archive/ckanapi-{{ version }}.tar.gz
    sha256: 96241d06c15afa6d2883ae2438359b4d6b7e59f0b308c13b0497805707935c95

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - setuptools
        - docopt
        - requests
        - simplejson

test:
  imports:
    - ckanapi
    - ckanapi.cli
    - ckanapi.tests

about:
  home: https://github.com/ckan/ckanapi
  license: MIT
  summary: 'A command line interface and Python module for accessing the CKAN Action API.'

extra:
    recipe-maintainers:
        - ocefpaf
