travis:
  secure:
    BINSTAR_TOKEN: co0QQisZHdMNJWN/9BpeRTYPHFcTTZg6O11Me7UdyKaCaynG46X5K7W2XeP88F2t/p0pDvQjOxSyc2G/XpVOq/WkxMrMz9bUiabk+PCYc++fkDE9hL5xY5UwttF349NKasq2aIZoFXP7rp/9T0jwsia71td72jnBQHMZbzzswy3pK1Ycj738BnP9gCq5Gsn1Z0ilNcHK5Z1oW6ZOUVC3wprlUf5Pk9SzT41+a7jl7Y9s+CAwfejtUvx4fs1Zq02OzWjtAaByDpAruN2L4uxb89gZfMkbFkf9/bYT3hohqEUhprS/VhRZEJ8f0RwRiBN7sy1v7Irp5vZO9Nzfj7cfKLxacwwfZvyiC5xP6T5/ppS/xWid+zhCxfx/NhBVIHwTzZ3cd9eLGoc8kyUQMTGEQgOne61YJkBYwmQxCPh1aK7uLnZHB5RqYDPNlbyTaxfCPr6hQpwL0hpWrLyXev62Z2mkEMCB/9RAAtuLaE3AfvmLrtPIp/GWwAFFTAzzi5Uus7u2VxfEacb2kFvBFW3OcfXyQWC6HiEuAt1UA9vFJRQEh8DYWZjnZbunRTaVa9PUfuRsVwb5yrb1xFdKY7feJg/hcCDpct6oR8PZM0A0CKfALovP6wCHZWwXO9cqyK7gih+Vr2Ob1RB0++B+EEVVEfoc97AiduJ1BgxYQ8k84fA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
